import iscreenLogo from "@/assets/iscreen-logo.png";
import hbomaxLogo from "@/assets/hbomax-logo.png";

export type Product = {
  id: string;
  name: string;
  tagline: string;
  price: number; // BDT — current selling price
  originalPrice?: number; // BDT — before-discount price (shown struck-through)
  duration: string;
  category: "streaming" | "editing" | "music" | "other";
  accent: string; // brand color for card glow
  logo: string; // logo URL
  logoFill?: boolean; // let logo fill the tile edge-to-edge
  rating?: number; // 0..5, one-decimal
  reviews?: number; // review count
  description?: string;
  features?: string[];
  warranty?: string;
};

// High-resolution brand logos via Clearbit (crisp, transparent PNG ~256px).
const logo = (domain: string) => `https://logo.clearbit.com/${domain}?size=512`;

export const products: Product[] = [
  {
    id: "netflix",
    name: "Netflix",
    tagline: "4K Ultra HD • 1 Screen",
    price: 250,
    originalPrice: 349,
    duration: "1 Month",
    category: "streaming",
    accent: "#e50914",
    logo: logo("netflix.com"),
    rating: 5.0,
    reviews: 428,
    description:
      "Enjoy Netflix in crystal-clear 4K Ultra HD with HDR & Dolby Atmos on a private profile. Access the full global library — Hollywood, K-Drama, anime and exclusive Netflix Originals — on any device.",
    features: [
      "Quality: 4K Ultra HD + HDR10 / Dolby Vision",
      "Screens: 1 dedicated private screen (PIN protected)",
      "Devices: TV, Mobile, Laptop, Tab, Firestick",
      "Region: Global library (US, UK, IN unlocked)",
      "Downloads: Offline viewing supported",
      "Delivery: Instant (within 5–30 minutes)",
      "Warranty: Full 30-day replacement guarantee",
    ],
    warranty: "30-Day Replacement Warranty",
  },
  {
    id: "prime",
    name: "Amazon Prime Video",
    tagline: "4K HDR • Private Profile",
    price: 180,
    originalPrice: 249,
    duration: "1 Month",
    category: "streaming",
    accent: "#00a8e1",
    logo: logo("primevideo.com"),
    rating: 4.9,
    reviews: 316,
    description:
      "Stream Prime Video in 4K UHD on your own private profile. Watch Amazon Originals, live sports, Hollywood blockbusters and Bollywood hits with unlimited downloads.",
    features: [
      "Quality: 4K UHD + HDR",
      "Screens: 1 private profile (yours only)",
      "Devices: Smart TV, Mobile, PC, Firestick, Console",
      "Region: US / IN library unlocked",
      "Downloads: Unlimited offline downloads",
      "Delivery: Instant activation",
      "Warranty: 30-day replacement guarantee",
    ],
    warranty: "30-Day Replacement Warranty",
  },
  {
    id: "yt-premium",
    name: "YouTube Premium",
    tagline: "Ad-free + YouTube Music",
    price: 220,
    originalPrice: 299,
    duration: "1 Month",
    category: "streaming",
    accent: "#ff0000",
    logo: logo("youtube.com"),
    rating: 5.0,
    reviews: 512,
    description:
      "Watch every YouTube video ad-free in up to 4K, play in background, download offline, and get full YouTube Music Premium — all on your own personal Google account.",
    features: [
      "Quality: Up to 4K 60fps",
      "Ads: 100% ad-free everywhere",
      "Background Play + Picture-in-Picture",
      "Includes: YouTube Music Premium",
      "Devices: All (Mobile, TV, Web, Tablet)",
      "Activated on YOUR own Gmail account",
      "Delivery: 5–30 minutes • 30-day warranty",
    ],
    warranty: "30-Day Replacement Warranty",
  },
  {
    id: "hbo",
    name: "HBO Max",
    tagline: "4K UHD • Shared Profile",
    price: 200,
    originalPrice: 279,
    duration: "1 Month",
    category: "streaming",
    accent: "#7c3aed",
    logo: hbomaxLogo,
    logoFill: true,
    rating: 4.8,
    reviews: 184,
    description:
      "Get HBO Max (Max) with access to Warner Bros. movies, HBO Originals, DC Universe and Harry Potter collection in 4K UHD with Dolby Atmos sound.",
    features: [
      "Quality: 4K UHD + Dolby Atmos",
      "Screens: 1 shared profile",
      "Content: HBO Originals, WB Movies, DC, Studio Ghibli",
      "Devices: TV, Mobile, PC, Firestick",
      "Downloads: Offline supported",
      "Delivery: Instant (within 30 minutes)",
      "Warranty: 30-day full replacement",
    ],
    warranty: "30-Day Replacement Warranty",
  },
  {
    id: "chorki",
    name: "Chorki",
    tagline: "All Bangla Originals",
    price: 150,
    originalPrice: 199,
    duration: "1 Month",
    category: "streaming",
    accent: "#ff6a00",
    logo: logo("chorki.com"),
    rating: 4.9,
    reviews: 267,
    description:
      "Bangladesh's premium OTT — watch every Chorki Original, exclusive Bangla films and web series in Full HD on any device.",
    features: [
      "Quality: Full HD 1080p",
      "Screens: 2 simultaneous streams",
      "Content: All Chorki Originals unlocked",
      "Devices: Mobile, TV, Web, Tab",
      "Downloads: Offline viewing on mobile",
      "Delivery: Instant activation",
      "Warranty: 30-day replacement",
    ],
    warranty: "30-Day Replacement Warranty",
  },
  {
    id: "bongo",
    name: "Bongo BOB",
    tagline: "Movies + Live TV",
    price: 130,
    originalPrice: 179,
    duration: "1 Month",
    category: "streaming",
    accent: "#00b894",
    logo: logo("bongobd.com"),
    rating: 4.7,
    reviews: 142,
    description:
      "Bongo BOB Premium — Bangla movies, natoks, live TV channels and kids content, all in one subscription.",
    features: [
      "Quality: Full HD 1080p",
      "Screens: 2 devices at a time",
      "Live TV: 40+ Bangla & international channels",
      "Devices: Mobile, Smart TV, Web",
      "Downloads: Available on mobile",
      "Delivery: Instant • 30-day warranty",
    ],
    warranty: "30-Day Replacement Warranty",
  },
  {
    id: "iscreen",
    name: "iScreen",
    tagline: "Premium Access",
    price: 140,
    originalPrice: 199,
    duration: "1 Month",
    category: "streaming",
    accent: "#e11d48",
    logo: iscreenLogo,
    logoFill: true,
    rating: 4.8,
    reviews: 96,
    description:
      "iScreen Premium — Bangladeshi streaming platform with exclusive originals, movies and live sports coverage.",
    features: [
      "Quality: Full HD 1080p",
      "Screens: 1 private access",
      "Content: iScreen Originals + Live Sports",
      "Devices: Mobile, TV, Web",
      "Delivery: Instant (5–30 min)",
      "Warranty: 30-day replacement guarantee",
    ],
    warranty: "30-Day Replacement Warranty",
  },
  {
    id: "hoichoi",
    name: "Hoichoi",
    tagline: "Bengali Web Series",
    price: 160,
    originalPrice: 219,
    duration: "1 Month",
    category: "streaming",
    accent: "#d63031",
    logo: logo("hoichoi.tv"),
    rating: 4.9,
    reviews: 231,
    description:
      "Hoichoi Premium — the largest Bengali OTT with 500+ original web series, films and shows from Kolkata & Dhaka.",
    features: [
      "Quality: Full HD 1080p",
      "Screens: 1 device at a time",
      "Content: 500+ Bengali originals & films",
      "Devices: Mobile, Smart TV, Web, Tab",
      "Downloads: Offline supported",
      "Delivery: Instant activation",
      "Warranty: 30-day replacement",
    ],
    warranty: "30-Day Replacement Warranty",
  },
  {
    id: "capcut",
    name: "CapCut Pro",
    tagline: "All Pro Effects Unlocked",
    price: 300,
    originalPrice: 449,
    duration: "1 Month",
    category: "editing",
    accent: "#111111",
    logo: logo("capcut.com"),
    rating: 5.0,
    reviews: 389,
    description:
      "CapCut Pro on your own account — unlock every premium effect, filter, transition, AI tool and 4K export with no watermark.",
    features: [
      "Export: 4K 60fps, no watermark",
      "All Pro Effects, Filters & Transitions",
      "AI Tools: Auto Caption, BG Remover, Enhance",
      "Cloud Storage: 100GB included",
      "Devices: Mobile + Desktop (PC/Mac)",
      "Activated on YOUR own account",
      "Delivery: Instant • 30-day warranty",
    ],
    warranty: "30-Day Replacement Warranty",
  },
  {
    id: "canva",
    name: "Canva Pro",
    tagline: "Team + Premium Assets",
    price: 280,
    originalPrice: 399,
    duration: "1 Month",
    category: "editing",
    accent: "#00c4cc",
    logo: logo("canva.com"),
    rating: 4.9,
    reviews: 254,
    description:
      "Canva Pro on your personal email — 100M+ premium assets, Magic AI tools, background remover, brand kit and 1TB cloud storage.",
    features: [
      "Access: 100M+ premium templates & elements",
      "Magic AI: Design, Write, Edit, Eraser",
      "Background Remover (1-click)",
      "Brand Kit + Team collaboration",
      "Storage: 1TB cloud",
      "Activated on YOUR own email",
      "Delivery: Instant • 30-day warranty",
    ],
    warranty: "30-Day Replacement Warranty",
  },
  {
    id: "spotify",
    name: "Spotify Premium",
    tagline: "Ad-free Music",
    price: 180,
    originalPrice: 249,
    duration: "1 Month",
    category: "music",
    accent: "#1db954",
    logo: logo("spotify.com"),
    rating: 5.0,
    reviews: 471,
    description:
      "Spotify Premium Individual on your own account — ad-free music, high-quality audio, unlimited skips and full offline downloads.",
    features: [
      "Quality: Very High 320kbps audio",
      "100% Ad-free streaming",
      "Unlimited Skips + Play any song",
      "Offline downloads on all devices",
      "Devices: Mobile, PC, TV, Speakers, Car",
      "Activated on YOUR own account",
      "Delivery: Instant • 30-day warranty",
    ],
    warranty: "30-Day Replacement Warranty",
  },
  {
    id: "chatgpt",
    name: "ChatGPT Plus",
    tagline: "GPT-5 + Priority Access",
    price: 1200,
    originalPrice: 1499,
    duration: "1 Month",
    category: "other",
    accent: "#10a37f",
    logo: logo("openai.com"),
    rating: 4.9,
    reviews: 178,
    description:
      "ChatGPT Plus on your own OpenAI account — access to the latest GPT-5 model, image generation, advanced voice, file uploads and priority speed even at peak hours.",
    features: [
      "Model: Latest GPT-5 + GPT-4o",
      "Image Generation (DALL·E 3)",
      "Advanced Voice + Vision mode",
      "File & PDF uploads, Code Interpreter",
      "Priority access during peak times",
      "Activated on YOUR own OpenAI account",
      "Delivery: Instant • 30-day warranty",
    ],
    warranty: "30-Day Replacement Warranty",
  },
];

export const categoryLabels: Record<Product["category"], string> = {
  streaming: "Streaming",
  editing: "Editing",
  music: "Music",
  other: "AI & Others",
};
